name: wpd
description: App for WPD.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  firebase_core: ^1.0.4
  firebase_auth: ^1.1.1
  cloud_firestore: ^1.0.1
  flutter_spinkit: ^5.0.0
  connectivity: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: VT323
      fonts:
        - asset: assets/fonts/VT323.ttf
